-- --------------------------------------------------------
-- 主机:                           public.debug.mydb.link
-- 服务器版本:                        5.6.16-log - Source distribution
-- 服务器操作系统:                      Linux
-- HeidiSQL 版本:                  11.0.0.5919
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 导出  表 packet_share.t_country 结构
DROP TABLE IF EXISTS `t_country`;
CREATE TABLE IF NOT EXISTS `t_country` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `iso_3` varchar(5) DEFAULT NULL COMMENT '三位缩写',
  `iso_2` varchar(50) DEFAULT NULL COMMENT '两位缩写',
  `name_en` varchar(50) DEFAULT NULL COMMENT '英文名称',
  `name_cn` varchar(50) DEFAULT NULL COMMENT '中文名称',
  `status` int(2) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `id` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=254 DEFAULT CHARSET=utf8;

-- 正在导出表  packet_share.t_country 的数据：~253 rows (大约)
DELETE FROM `t_country`;
/*!40000 ALTER TABLE `t_country` DISABLE KEYS */;
INSERT INTO `t_country` (`id`, `iso_3`, `iso_2`, `name_en`, `name_cn`, `status`) VALUES
	(1, 'CHN', 'CN', 'China', '中国', 0),
	(2, 'AFG', 'AF', 'Afghanistan', '阿富汗', 0),
	(3, 'ALA', 'AX', 'Aland', '奥兰', 0),
	(4, 'ALB', 'AL', 'Albania', '阿尔巴尼亚', 0),
	(5, 'DZA', 'DZ', 'Algeria', '阿尔及利亚', 0),
	(6, 'ASM', 'AS', 'American Samoa', '美属萨摩亚', 0),
	(7, 'AND', 'AD', 'Andorra', '安道尔', 0),
	(8, 'AGO', 'AO', 'Angola', '安哥拉', 0),
	(9, 'AIA', 'AI', 'Anguilla', '安圭拉', 0),
	(10, 'ATG', 'AG', 'Antigua and Barbuda', '安提瓜和巴布达', 0),
	(11, 'ARG', 'AR', 'Argentina', '阿根廷', 0),
	(12, 'ARM', 'AM', 'Armenia', '亚美尼亚', 0),
	(13, 'ABW', 'AW', 'Aruba', '阿鲁巴', 0),
	(14, 'AUS', 'AU', 'Australia', '澳大利亚', 0),
	(15, 'AUT', 'AT', 'Austria', '奥地利', 0),
	(16, 'AZE', 'AZ', 'Azerbaijan', '阿塞拜疆', 0),
	(17, 'BHS', 'BS', 'Bahamas', '巴哈马', 0),
	(18, 'BHR', 'BH', 'Bahrain', '巴林', 0),
	(19, 'BGD', 'BD', 'Bangladesh', '孟加拉国', 0),
	(20, 'BRB', 'BB', 'Barbados', '巴巴多斯', 0),
	(21, 'BLR', 'BY', 'Belarus', '白俄罗斯', 0),
	(22, 'BEL', 'BE', 'Belgium', '比利时', 0),
	(23, 'BLZ', 'BZ', 'Belize', '伯利兹', 0),
	(24, 'BEN', 'BJ', 'Benin', '贝宁', 0),
	(25, 'BMU', 'BM', 'Bermuda', '百慕大', 0),
	(26, 'BTN', 'BT', 'Bhutan', '不丹', 0),
	(27, 'BOL', 'BO', 'Bolivia', '玻利维亚', 0),
	(28, 'BIH', 'BA', 'Bosnia and Herzegovina', '波黑', 0),
	(29, 'BWA', 'BW', 'Botswana', '博茨瓦纳', 0),
	(30, 'BVT', 'BV', 'Bouvet Island', '布韦岛', 0),
	(31, 'BRA', 'BR', 'Brazil', '巴西', 0),
	(32, 'IOT', 'IO', 'British Indian Ocean Territory', '英属印度洋领地', 0),
	(33, 'BSA', 'GB', 'British Sovereign Base Areas', '英属基地区', 0),
	(34, 'VGB', 'VG', 'British Virgin Islands', '英属维尔京群岛', 0),
	(35, 'BRN', 'BN', 'Brunei', '文莱', 0),
	(36, 'BGR', 'BG', 'Bulgaria', '保加利亚', 0),
	(37, 'BFA', 'BF', 'Burkina Faso', '布基纳法索', 0),
	(38, 'BDI', 'BI', 'Burundi', '布隆迪', 0),
	(39, 'KHM', 'KH', 'Cambodia', '柬埔寨', 0),
	(40, 'CMR', 'CM', 'Cameroon', '喀麦隆', 0),
	(41, 'CAN', 'CA', 'Canada', '加拿大', 0),
	(42, 'CPV', 'CV', 'Cape Verde', '佛得角', 0),
	(43, 'BES', 'BQ', 'Caribbean Netherlands', '加勒比荷兰', 0),
	(44, 'CYM', 'KY', 'Cayman Islands', '开曼群岛', 0),
	(45, 'CAF', 'CF', 'Central African Republic', '中非共和国', 0),
	(46, 'TCD', 'TD', 'Chad', '乍得', 0),
	(47, 'CHL', 'CL', 'Chile', '智利', 0),
	(48, 'CXR', 'CX', 'Christmas Island', '圣诞岛', 0),
	(49, 'CCK', 'CC', 'Cocos Islands', '科科斯群岛', 0),
	(50, 'COL', 'CO', 'Colombia', '哥伦比亚', 0),
	(51, 'COM', 'KM', 'Comoros', '科摩罗', 0),
	(52, 'COK', 'CK', 'Cook Islands', '库克群岛', 0),
	(53, 'CRI', 'CR', 'Costa Rica', '哥斯达黎加', 0),
	(54, 'CIV', 'CI', 'Cote d\'Ivoire', '科特迪瓦', 0),
	(55, 'HRV', 'HR', 'Croatia', '克罗地亚', 0),
	(56, 'CUB', 'CU', 'Cuba', '古巴', 0),
	(57, 'CUW', 'CW', 'Curasao', '库拉索', 0),
	(58, 'CYP', 'CY', 'Cyprus', '塞浦路斯', 0),
	(59, 'UNZ', 'CY', 'Cyprus UN Buffer Zone', '塞浦路斯联合国缓冲区', 0),
	(60, 'CZE', 'CZ', 'Czech Republic', '捷克共和国', 0),
	(61, 'COD', 'CD', 'Democratic Republic of the Congo', '刚果民主共和国', 0),
	(62, 'DNK', 'DK', 'Denmark', '丹麦', 0),
	(63, 'DJI', 'DJ', 'Djibouti', '吉布提', 0),
	(64, 'DMA', 'DM', 'Dominica', '多米尼克', 0),
	(65, 'DOM', 'DO', 'Dominican Republic', '多米尼加共和国', 0),
	(66, 'TLS', 'TL', 'East Timor', '东帝汶', 0),
	(67, 'ECU', 'EC', 'Ecuador', '厄瓜多尔', 0),
	(68, 'EGY', 'EG', 'Egypt', '埃及', 0),
	(69, 'SLV', 'SV', 'El Salvador', '萨尔瓦多', 0),
	(70, 'GBR', 'GB', 'England', '英格兰', 0),
	(71, 'GNQ', 'GQ', 'Equatorial Guinea', '赤道几内亚', 0),
	(72, 'ERI', 'ER', 'Eritrea', '厄立特里亚', 0),
	(73, 'EST', 'EE', 'Estonia', '爱沙尼亚', 0),
	(74, 'ETH', 'ET', 'Ethiopia', '埃塞俄比亚', 0),
	(75, 'FLK', 'FK', 'Falkland Islands', '福克兰群岛', 0),
	(76, 'FRO', 'FO', 'Faroe Islands', '法罗群岛', 0),
	(77, 'FJI', 'FJ', 'Fiji', '斐济', 0),
	(78, 'FIN', 'FI', 'Finland', '芬兰', 0),
	(79, 'FRA', 'FR', 'France', '法国', 0),
	(80, 'GUF', 'GF', 'French Guiana', '法属圭亚那', 0),
	(81, 'PYF', 'PF', 'French Polynesia', '法属波利尼西亚', 0),
	(82, 'ATF', 'TF', 'French Southern Territories', '法属南部领地', 0),
	(83, 'GAB', 'GA', 'Gabon', '加蓬', 0),
	(84, 'GMB', 'GM', 'Gambia', '冈比亚', 0),
	(85, 'JSD', 'JS', 'Gaza Strip', '加沙地带', 0),
	(86, 'GEO', 'GE', 'Georgia', '格鲁吉亚', 0),
	(87, 'DEU', 'DE', 'Germany', '德国', 0),
	(88, 'GHA', 'GH', 'Ghana', '加纳', 0),
	(89, 'GIB', 'GI', 'Gibraltar', '直布罗陀', 0),
	(90, 'GRC', 'GR', 'Greece', '希腊', 0),
	(91, 'GRL', NULL, 'Greenland', '格陵兰（丹）', 0),
	(92, 'GRD', 'GD', 'Grenada', '格林纳达', 0),
	(93, 'GLP', 'GP', 'Guadeloupe', '瓜德罗普', 0),
	(94, 'GUM', 'GU', 'Guam', '关岛', 0),
	(95, 'GTM', 'GT', 'Guatemala', '危地马拉', 0),
	(96, 'GGY', 'GG', 'Guernsey', '根西岛', 0),
	(97, 'GIN', 'GN', 'Guinea', '几内亚', 0),
	(98, 'GNB', 'GW', 'Guinea-Bissau', '几内亚比绍', 0),
	(99, 'GUY', 'GY', 'Guyana', '圭亚那', 0),
	(100, 'HTI', 'HT', 'Haiti', '海地', 0),
	(101, 'HMD', 'HM', 'Heard Island and McDonald Islands', '赫德岛和麦克唐纳群岛', 0),
	(102, 'HND', 'HN', 'Honduras', '洪都拉斯', 0),
	(103, 'HUN', 'HU', 'Hungary', '匈牙利', 0),
	(104, 'ISL', 'IS', 'Iceland', '冰岛', 0),
	(105, 'IND', 'IN', 'India', '印度', 0),
	(106, 'IDN', 'ID', 'Indonesia', '印度尼西亚', 0),
	(107, 'IRN', 'IR', 'Iran', '伊朗', 0),
	(108, 'IRQ', 'IQ', 'Iraq', '伊拉克', 0),
	(109, 'IRL', 'IE', 'Ireland', '爱尔兰', 0),
	(110, 'IMN', 'IM', 'Isle of Man', '马恩岛', 0),
	(111, 'ISR', 'IL', 'Israel', '以色列', 0),
	(112, 'ITA', 'IT', 'Italy', '意大利', 0),
	(113, 'JAM', 'JM', 'Jamaica', '牙买加', 0),
	(114, 'JPN', 'JP', 'Japan', '日本', 0),
	(115, 'JEY', 'JE', 'Jersey', '泽西岛', 0),
	(116, 'JOR', 'JO', 'Jordan', '约旦', 0),
	(117, 'KAZ', 'KZ', 'Kazakhstan', '哈萨克斯坦', 0),
	(118, 'KEN', 'KE', 'Kenya', '肯尼亚', 0),
	(119, 'KIR', 'KI', 'Kiribati', '基里巴斯', 0),
	(120, 'XKS', 'XK', 'Kosovo', '科索沃', 0),
	(121, 'KWT', 'KW', 'Kuwait', '科威特', 0),
	(122, 'KGZ', 'KG', 'Kyrgyzstan', '吉尔吉斯斯坦', 0),
	(123, 'LAO', 'LA', 'Laos', '老挝', 0),
	(124, 'LVA', 'LV', 'Latvia', '拉脱维亚', 0),
	(125, 'LBN', 'LB', 'Lebanon', '黎巴嫩', 0),
	(126, 'LSO', 'LS', 'Lesotho', '莱索托', 0),
	(127, 'LBR', 'LR', 'Liberia', '利比里亚', 0),
	(128, 'LBY', 'LY', 'Libya', '利比亚', 0),
	(129, 'LIE', 'LI', 'Liechtenstein', '列支敦士登', 0),
	(130, 'LTU', 'LT', 'Lithuania', '立陶宛', 0),
	(131, 'LUX', 'LU', 'Luxembourg', '卢森堡', 0),
	(132, 'MKD', 'MK', 'Macedonia', '马其顿', 0),
	(133, 'MDG', 'MG', 'Madagascar', '马达加斯加', 0),
	(134, 'MWI', 'MW', 'Malawi', '马拉维', 0),
	(135, 'MYS', 'MY', 'Malaysia', '马来西亚', 0),
	(136, 'MDV', 'MV', 'Maldives', '马尔代夫', 0),
	(137, 'MLI', 'ML', 'Mali', '马里', 0),
	(138, 'MLT', 'MT', 'Malta', '马耳他', 0),
	(139, 'MHL', 'MH', 'Marshall Islands', '马绍尔群岛', 0),
	(140, 'MTQ', 'MQ', 'Martinique', '马提尼克', 0),
	(141, 'MRT', 'MR', 'Mauritania', '毛里塔尼亚', 0),
	(142, 'MUS', 'MU', 'Mauritius', '毛里求斯', 0),
	(143, 'MYT', 'YT', 'Mayotte', '马约特', 0),
	(144, 'MEX', 'MX', 'Mexico', '墨西哥', 0),
	(145, 'FSM', 'FM', 'Micronesia', '密克罗尼西亚', 0),
	(146, 'MDA', 'MD', 'Moldova', '摩尔多瓦', 0),
	(147, 'MCO', 'MC', 'Monaco', '摩纳哥', 0),
	(148, 'MNG', 'MN', 'Mongolia', '蒙古', 0),
	(149, 'MNE', 'ME', 'Montenegro', '黑山', 0),
	(150, 'MSR', 'MS', 'Montserrat', '蒙特塞拉特', 0),
	(151, 'MAR', 'MA', 'Morocco', '摩洛哥', 0),
	(152, 'MOZ', 'MZ', 'Mozambique', '莫桑比克', 0),
	(153, 'MMR', 'MM', 'Myanmar', '缅甸', 0),
	(154, 'NAM', 'NA', 'Namibia', '纳米比亚', 0),
	(155, 'NRU', 'NR', 'Nauru', '瑙鲁', 0),
	(156, 'NPL', 'NP', 'Nepal', '尼泊尔', 0),
	(157, 'NLD', 'NL', 'Netherlands', '荷兰', 0),
	(158, 'NCL', 'NC', 'New Caledonia', '新喀里多尼亚', 0),
	(159, 'NZL', 'NZ', 'New Zealand', '新西兰', 0),
	(160, 'NIC', 'NI', 'Nicaragua', '尼加拉瓜', 0),
	(161, 'NER', 'NE', 'Niger', '尼日尔', 0),
	(162, 'NGA', 'NG', 'Nigeria', '尼日利亚', 0),
	(163, 'NIU', 'NU', 'Niue', '纽埃', 0),
	(164, 'NFK', 'NF', 'Norfolk Island', '诺福克岛', 0),
	(165, 'PRK', 'KP', 'North Korea', '朝鲜', 0),
	(166, 'GBR', 'GB', 'Northern Ireland', '北爱尔兰', 0),
	(167, 'MNP', 'MP', 'Northern Mariana Islands', '北马里亚纳群岛', 0),
	(168, 'NOR', 'NO', 'Norway', '挪威', 0),
	(169, 'OMN', 'OM', 'Oman', '阿曼', 0),
	(170, 'PAK', 'PK', 'Pakistan', '巴基斯坦', 0),
	(171, 'PLW', 'PW', 'Palau', '帕劳', 0),
	(172, 'PSE', 'PS', 'Palestina', '巴勒斯坦', 0),
	(173, 'PAN', 'PA', 'Panama', '巴拿马', 0),
	(174, 'PNG', 'PG', 'Papua New Guinea', '巴布亚新几内亚', 0),
	(175, 'PRY', 'PY', 'Paraguay', '巴拉圭', 0),
	(176, 'PER', 'PE', 'Peru', '秘鲁', 0),
	(177, 'PHL', 'PH', 'Philippines', '菲律宾', 0),
	(178, 'PCN', 'PN', 'Pitcairn Islands', '皮特凯恩群岛', 0),
	(179, 'POL', 'PL', 'Poland', '波兰', 0),
	(180, 'PRT', 'PT', 'Portugal', '葡萄牙', 0),
	(181, 'PRI', 'PR', 'Puerto Rico', '波多黎各', 0),
	(182, 'QAT', 'QA', 'Qatar', '卡塔尔', 0),
	(183, 'COG', 'CG', 'Republic of the Congo', '刚果共和国', 0),
	(184, 'REU', 'RE', 'Reunion', '留尼汪', 0),
	(185, 'ROU', 'RO', 'Romania', '罗马尼亚', 0),
	(186, 'RUS', 'RU', 'Russia', '俄罗斯', 0),
	(187, 'RWA', 'RW', 'Rwanda', '卢旺达', 0),
	(188, 'SHN', 'SH', 'Saint Helena, Ascension and Tristan da Cunha', '圣赫勒拿、阿森松和特里斯坦-达库尼亚', 0),
	(189, 'KNA', 'KN', 'Saint Kitts and Nevis', '圣基茨和尼维斯', 0),
	(190, 'LCA', 'LC', 'Saint Lucia', '圣卢西亚', 0),
	(191, 'VCT', 'VC', 'Saint Vincent and the Grenadines', '圣文森特和格林纳丁斯', 0),
	(192, 'BLM', 'BL', 'Saint-Barthelemy', '圣巴泰勒米', 0),
	(193, 'MAF', 'MF', 'Saint-Martin', '法属圣马丁', 0),
	(194, 'SPM', 'PM', 'Saint-Pierre and Miquelon', '圣皮埃尔和密克隆群岛', 0),
	(195, 'WSM', 'WS', 'Samoa', '萨摩亚', 0),
	(196, 'SMR', 'SM', 'San Marino', '圣马力诺', 0),
	(197, 'STP', 'ST', 'Sao Tome and Principe', '圣多美和普林西比', 0),
	(198, 'SAU', 'SA', 'Saudi Arabia', '沙特阿拉伯', 0),
	(199, 'SCO', 'GB', 'Scotland', '苏格兰', 0),
	(200, 'SEN', 'SN', 'Senegal', '塞内加尔', 0),
	(201, 'SRB', 'RS', 'Serbia', '塞尔维亚', 0),
	(202, 'SYC', 'SC', 'Seychelles', '塞舌尔', 0),
	(203, 'SLE', 'SL', 'Sierra Leone', '塞拉利昂', 0),
	(204, 'SGP', 'SG', 'Singapore', '新加坡', 0),
	(205, 'SXM', 'SX', 'Sint Maarten', '荷属圣马丁', 0),
	(206, 'SVK', 'SK', 'Slovakia', '斯洛伐克', 0),
	(207, 'SVN', 'SI', 'Slovenia', '斯洛文尼亚', 0),
	(208, 'SLB', 'SB', 'Solomon Islands', '所罗门群岛', 0),
	(209, 'SOM', 'SO', 'Somalia', '索马里', 0),
	(210, 'ZAF', 'ZA', 'South Africa', '南非', 0),
	(211, 'SGS', 'GS', 'South Georgia and the South Sandwich Islands', '南乔治亚和南桑威奇群岛', 0),
	(212, 'KOR', 'KR', 'South Korea', '韩国', 0),
	(213, 'SSD', 'SS', 'South Sudan', '南苏丹', 0),
	(214, 'ESP', 'ES', 'Spain', '西班牙', 0),
	(215, 'LKA', 'LK', 'Sri Lanka', '斯里兰卡', 0),
	(216, 'SDN', 'SD', 'Sudan', '苏丹', 0),
	(217, 'SUR', 'SR', 'Suriname', '苏里南', 0),
	(218, 'SJM', 'SJ', 'Svalbard and Jan Mayen', '斯瓦尔巴和扬马延', 0),
	(219, 'SWZ', 'SZ', 'Swaziland', '斯威士兰', 0),
	(220, 'SWE', 'SE', 'Sweden', '瑞典', 0),
	(221, 'CHE', 'CH', 'Switzerland', '瑞士', 0),
	(222, 'SYR', 'SY', 'Syria', '叙利亚', 0),
	(223, 'TJK', 'TJ', 'Tajikistan', '塔吉克斯坦', 0),
	(224, 'TZA', 'TZ', 'Tanzania', '坦桑尼亚', 0),
	(225, 'THA', 'TH', 'Thailand', '泰国', 0),
	(226, 'TGO', 'TG', 'Togo', '多哥', 0),
	(227, 'TKL', 'TK', 'Tokelau', '托克劳', 0),
	(228, 'TON', 'TO', 'Tonga', '汤加', 0),
	(229, 'TTO', 'TT', 'Trinidad and Tobago', '特立尼达和多巴哥', 0),
	(230, 'TUN', 'TN', 'Tunisia', '突尼斯', 0),
	(231, 'TUR', 'TR', 'Turkey', '土耳其', 0),
	(232, 'TRN', 'CY', 'Turkish Republic of Northern Cyprus', '北塞浦路斯土耳其共和国', 0),
	(233, 'TKM', 'TM', 'Turkmenistan', '土库曼斯坦', 0),
	(234, 'TCA', 'TC', 'Turks and Caicos Islands', '特克斯和凯科斯群岛', 0),
	(235, 'TUV', 'TV', 'Tuvalu', '图瓦卢', 0),
	(236, 'UGA', 'UG', 'Uganda', '乌干达', 0),
	(237, 'UKR', 'UA', 'Ukraine', '乌克兰', 0),
	(238, 'ARE', 'AE', 'United Arab Emirates', '阿联酋', 0),
	(239, 'USA', 'US', 'United States', '美国', 0),
	(240, 'UMI', 'UM', 'United States Minor Outlying Islands', '美国本土外小岛屿', 0),
	(241, 'URY', 'UY', 'Uruguay', '乌拉圭', 0),
	(242, 'UZB', 'UZ', 'Uzbekistan', '乌兹别克斯坦', 0),
	(243, 'VUT', 'VU', 'Vanuatu', '瓦努阿图', 0),
	(244, 'VAT', 'VA', 'Vatican City', '梵蒂冈', 0),
	(245, 'VEN', 'VE', 'Venezuela', '委内瑞拉', 0),
	(246, 'VNM', 'VN', 'Viet Nam', '越南', 0),
	(247, 'VIR', 'VI', 'Virgin Islands', '美属维尔京群岛', 0),
	(248, 'WLS', 'GB', 'Wales', '威尔士', 0),
	(249, 'WLF', 'WF', 'Wallis and Futuna', '瓦利斯和富图纳', 0),
	(250, 'ESH', 'EH', 'Western Sahara', '西撒哈拉', 0),
	(251, 'YEM', 'YE', 'Yemen', '也门', 0),
	(252, 'ZMB', 'ZM', 'Zambia', '赞比亚', 0),
	(253, 'ZWE', 'ZW', 'Zimbabwe', '津巴布韦', 0);
/*!40000 ALTER TABLE `t_country` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
